added metrics to wf-script

diff --git a/scripts/wf-script b/scripts/wf-script
--- a/scripts/wf-script
+++ b/scripts/wf-script
@@ -1,7 +1,7 @@
 #!/bin/bash
 echo "Configuring wavefront-cli..."
 wf config envvars > /dev/null
-wf source list --limit 1
+wf source list --limit 1 > /dev/null
 
 exitcode=$?
 if [ $exitcode -eq 0 ]; then
@@ -23,12 +23,56 @@ echo "Proxy $WAVEFRONT_PROXY has id number: $proxy_id"
 
 # METRIC
 
-echo "Searching for recent metrics starting with $METRIC"
-wf spy points --prefix="$METRIC" --end-after=60
+# echo "Searching for recent metrics starting with $METRIC"
+# Very slow
+# wf spy points --prefix="$METRIC" --end-after=60
 
-# tanzu.vmware.com/serverless.contour.contour.build.info.gauge
-# tanzu.vmware.com/serverless.knative.activator.client.results.counter
-# tanzu.vmware.com/serverless.knative.autoscaler.client.results.counter
-# tanzu.vmware.com/serverless.knative.contour.ingress.controller.client.results.counter
-# tanzu.vmware.com/serverless.knative.controller.client.results.counter
-# tanzu.vmware.com/serverless.knative.webhook.client.results.counter
+declare -a metric_list=(
+  "contour"
+  "kn_activator"
+  "kn_autoscaler"
+  "kn_contour"
+  "kn_controller"
+  "kn_webhook"
+)
+
+wf query "ts(tanzu.vmware.com/serverless.contour.contour.build.info.gauge)" -f json > contour_response 2> contour_error
+wf query "ts(tanzu.vmware.com/serverless.knative.activator.client.results.counter)" -f json > kn_activator_response 2> kn_activator_error
+wf query "ts(tanzu.vmware.com/serverless.knative.autoscaler.client.results.counter)" -f json > kn_autoscaler_response 2> kn_autoscaler_error
+wf query "ts(tanzu.vmware.com/serverless.knative.contour.ingress.controller.client.results.counter)" -f json > kn_contour_response 2> kn_contour_error
+wf query "ts(tanzu.vmware.com/serverless.knative.controller.client.results.counter)" -f json > kn_controller_response 2> kn_controller_error
+wf query "ts(tanzu.vmware.com/serverless.knative.webhook.client.results.counter)" -f json > kn_webhook_response 2> kn_webhook_error
+
+failed=false
+for metric in "${metric_list[@]}"; do
+  echo -e "\n********** ${metric} **********"
+
+  now=$(date +%s)
+  last_reported=$(jq '.timeseries[0].data[-1][0]' "${metric}_response")
+  time_elapsed=$((now - last_reported))
+
+  if [ -z "$last_reported" ] || [ "$last_reported" == "null" ]; then
+    failed=true
+  else
+    echo "Time elapsed since $last_reported and $now: $time_elapsed"
+  fi
+
+  if (( time_elapsed <= 1200 )); then
+    echo "INFO: $time_elapsed seconds since last report of: $metric"
+  else
+    echo "*** WARNING ***: Last reported timestamp: $last_reported. Time elapsed: $time_elapsed"
+    failed=true
+  fi
+
+  if [ -s "${metric}"_error ]; then
+    failed=true
+    echo "Error message from 'wf query for ${metric}:"
+    echo -e "\n----------------------------------------------"
+    cat "${metric}_error"
+    echo -e "\n----------------------------------------------"
+  fi
+done
+
+if [ $failed ]; then
+  exit 1
+fi
